// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package no.iterate.konferanse2014.guava.beans;

import java.util.Date;

public class BeregningBuilder extends BeregningBuilderBase<BeregningBuilder> {
	public static BeregningBuilder beregning() {
		return new BeregningBuilder();
	}

	public BeregningBuilder() {
		super(new Beregning());
	}

	public Beregning build() {
		return getInstance();
	}
}

class BeregningBuilderBase<GeneratorT extends BeregningBuilderBase<GeneratorT>> {
	private Beregning instance;

	protected BeregningBuilderBase(Beregning aInstance) {
		instance = aInstance;
	}

	protected Beregning getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAksjonsDato(Date aValue) {
		instance.setAksjonsDato(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSendtF2100Tidspunkt(Date aValue) {
		instance.setSendtF2100Tidspunkt(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNumBeregningsrekkefolge(Integer aValue) {
		instance.setNumBeregningsrekkefolge(aValue);

		return (GeneratorT) this;
	}
}
