// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package no.iterate.konferanse2014.guava.beans;

import java.util.Date;

public class ForventetYtelseBuilder extends
		ForventetYtelseBuilderBase<ForventetYtelseBuilder> {
	public static ForventetYtelseBuilder forventetYtelse() {
		return new ForventetYtelseBuilder();
	}

	public ForventetYtelseBuilder() {
		super(new ForventetYtelse());
	}

	public ForventetYtelse build() {
		return getInstance();
	}
}

class ForventetYtelseBuilderBase<GeneratorT extends ForventetYtelseBuilderBase<GeneratorT>> {
	private ForventetYtelse instance;

	protected ForventetYtelseBuilderBase(ForventetYtelse aInstance) {
		instance = aInstance;
	}

	protected ForventetYtelse getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDekningsnummer(Dekningsnummer aValue) {
		instance.setDekningsnummer(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPensjonFradato(Date aValue) {
		instance.setPensjonFradato(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUtlopsDato(Date aValue) {
		instance.setUtlopsDato(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRedusertPensjon(int aValue) {
		instance.setRedusertPensjon(aValue);

		return (GeneratorT) this;
	}
}
